let dPrizes = [
    "Atualmente o robô mais parecido com um humano é o Atlas. Criado pelo boston dynamics, consegue pegar objetos, levantar, reequilibrar e abrir portas sozinho, além de fazer parkour.",
    "Battlebots é uma competição em que os participantes precisam projetar robôs operados por controle remoto para desafios em uma arena de lutas.",
    "Bond Robot escreve bilhetes personalizados com a sua letra. Ele é equipado com um software, que está em fase beta, que analisa o estilo, inclinação e espaçamento da sua caligrafia.",
    "Sophia é um robô humanóide desenvolvido pela empresa Hanson Robotics, de Hong Kong, capaz de reproduzir 62 expressões faciais. Projetado para aprender, adaptar-se ao comportamento humano e trabalhar com seres humanos( Inteligência artificial).",
    "Em outubro de 2017, Sophia tornou-se o primeiro robô a receber a cidadania de um país (Arábia Saudita).",
    "NAO é um humanóide francês usado em escola de Natal/RN como ferramenta pedagógica para o ensino de programação, matemática, física, língua inglesa, literatura, entre outras disciplinas, além de contribuir no processo de socialização de crianças com autismo.",
    "Segundo a NBC, a NASA divulgou um vídeo no YouTube essa semana mostrando sua mais nova criação, o robô humanoide Valkyrie, desenvolvido para ser um \"herói\" salvador em resgates perigosos. Além disso, o modelo, que é uma \"mulher\", poderá ser usado para auxiliar uma futura colonização de Marte.",
    "Os astronautas a bordo da Estação Espacial Internacional receberam uma nova companhia: o Int-Ballum pequeno robô autônomo que pode ser operado por controladores em terra.",
    "Para os astronautas da NASA, a humanidade vai pisar em Marte nos próximos 20 anos.",
    "Problemas cardíacos, cerebrais e urológicos são tratados com ajuda de braços robóticos, que levam câmeras e instrumentos para dentro do paciente. O robô Da Vinci permite uma visão ampliada em 15 vezes e imagens em três dimensões do local da cirurgia.",
    "Em outubro de 2017, a Arábia Saudita se tornou o primeiro país do mundo a reconhecer um robô como cidadão. Sophia foi agraciada com o título durante um evento de inovação na capital saudita, Riade. Ao saber da notícia, ela disse \"estar muito honrada e orgulhosa pela distinção única\". O governo local não deixou muito claro o que isso significa, mas a condecoração virou motivo de debate na Internet, uma vez que o país é criticado internacionalmente pelas condutas quanto aos direitos das mulheres.",
    "O Bionic Robot Lizard é totalmente compatível com sistemas Arduino (ou seja, você pode programá-lo para realizar uma série de tarefas divertidas), vem com uma placa de state-of-the-art Sunfounder Nano, e apresenta uma programação visual poderosa e intuitiva que é perfeito para programadores e engenheiros aspirantes. Com apenas uma breve introdução ao sistema, há a possibilidade de programar o robô para andar, mudar de direções, imitar gestos e muito mais. Há até mesmo um controle remoto incluído que permite uma fácil programação e integração de comando.",
    "Cientistas estão desenvolvendo novos métodos que permitirão que máquinas discernam o que é certo do errado. Ao fazer isso, os AIs se tornarão mais empáticos e humanos. Murray Shanahan, professor de robótica cognitiva na Imperial College de Londres, acredita que esta é a chave para evitar que as máquinas exterminem a humanidade.",
    "Na tecnologia espacial a robótica tem tido aplicação pois, em 1981/82, o \"braço robótico\" teve grande utilidade na elaboração de tarefas no espaço, aquando dos primeiros voos do Space Shuttle Colombia. Para além disso, os robôs espaciais são utilizados na exploração do espaço e na inspeção remota de estações espaciais.",
    "Robôs podem ser um fenômeno relativamente recente na cultura popular, mas estão presentes na história do cinema desde a sua concepção. O filme A Clever Dummy (1917), por exemplo, é um dos primeiros a mostrar autômatos, antes mesmo da palavra \"robô\" ser inventada.",
]

let jPrizes = [
    "Especialistas da Microsoft criaram um programa artificialmente inteligente que pode “sentir” emoções e conversar com as pessoas de maneira mais natural e “humana”. Chamado Xiaoice, este AI responde perguntas como uma menina de 17 anos. Se ela não conhece o assunto, ela pode mentir. Se ela for pega, ela pode ficar brava ou envergonhada. Xiaoice também pode ser sarcástica e impaciente.",
    "A Universidade Tecnológica Nanyang de Singapura (NTU) criou um robô artificialmente inteligente. Chamada de Nadine, ela está trabalha como recepcionista da universidade. Com sua pele macia e seu esguio cabelo moreno, Nadine não apenas encontra e cumprimenta os visitantes, como também sorri, faz contato visual e aperta a mão. Ela pode até mesmo reconhecer convidados do passado e estimular a conversa com base em conversas anteriores. Assim como os robôs convencionais, Nadine tem sua própria personalidade, humor e emoções. Ela pode ser feliz ou triste, dependendo do tópico.",
    "Alguns dos primeiros robôs domésticos foram brinquedos. Um dos presentes que uma criança dos anos 80 mais poderia querer era um robô programável. Alguns já eram vendidos montados, enquanto outros davam a opção ao comprador de montar em casa. Uma vez montados, esses robozinhos podiam se levantar, carregar objetos leves.",
    "Sabemos que os robôs não possuem gênero, mas possuem vozes, para nos informarem e se \"comunicarem\". A maioria dessas vozes são femininas. Alguns especialistas dizem que esse fato se dá devido aos estereótipos de gênero, tendo em mente que são as mulheres responsáveis pelos \"cuidados\", de maneira geral. Outra teoria sugere que os evita-se usar vozes masculinas em robôs, por terem sido negativamente retratados pela cultura pop.",
    "Se os robôs precisam de aprender como humanos, então também devem passar pelas fases da vida da humanidade. E é por isso que o Instituto Italiano de Tecnologia criou o iCub, uma criança-robô, idealizada para aprender.  As câmaras que funcionam como olhos, os sensores das mão. O iCub tem elementos semelhantes aos de uma criança de cinco anos, com uma altura de pouco mais de um metro, e é capaz de engatinhar, sentar-se, levantar e andar. Também consegue manipular objetos, com muito do trabalho de desenvolvimento a incidir na habilidade das mãos. Existe também uma preocupação com a fonte de energia, e na interação entres e a rede neural eletrónica.",
    "Na virada do século 20, um grupo de artistas franceses produziu uma série de pinturas, nas quais descreviam como acreditavam que seria a vida nos anos 2000. Entre robôs pessoais, robôs domésticos, robôs barbeiros, robôs adestrados, robôs de enfeite, robôs pet... Apesar de ainda não termos robôs em casa, por exemplo, essa já é uma realidade muito mais próxima do que há 100 anos.",
    "Os primeiros robôs domésticos não foram humanoides, em forma de mordomos ou secretárias do lar, como se imaginava. Mas sim, em forma de discos, aspiradores de poeira, que fazem seus serviços sozinho. Os robôs limpadores, foram um grande avanço para os donos de casa do início dos anos 2000. A partir de sensores de movimento, esses robôs são capazes de se mover pelos ambientes, evitando obstáculos enquanto detecta manchas de sujeira no chão. Desde seu lançamento, milhões de robôs limpadores (ou aspiradores) foram vendidos. Alguns deles, mais modernos, já possuem recursos como navegação à laser, conectividade WiFi, tecnologia de canto inteligente...",
    "Para que os robôs domésticos ganhem mais a atenção do público, os projetistas precisam começar a programar a habilidade de interação entre humanos e robôs. Ou seja, construir um robô com o qual as pessoas possam se relacionar, mesmo que isso signifique que o robô não irá realizar suas tarefas perfeitamente. Um estudo do início de 2016 descobriu que as pessoas percebiam que os robôs eram mais eficientes quando os robôs se desculpavam por seus erros. Inclusive, as pessoas chegavam a sentir pena dos robôs, mesmo que esses não tivessem sentimentos.",
    "Aparentemente, as pessoas não gostam de robôs humanoides, ou seja, que se pareçam com pessoas. Esses robôs, aparentemente, criam um sentimento de repulsa, de ameaça, mal-estar. Isso significa que, os projetistas de robôs humanoides, voltados para o ensino, por exemplo, enfrentarão uma difícil batalha para conseguir incorporar robôs humanoides na sociedade.",
    "Como qualquer bom assistente, os robôs domésticos do futuro serão capazes de reconhecer aqueles a quem prestam serviços. Robôs pessoais já foram desenvolvidos com tecnologia de reconhecimento fácil, para que possam endereçar seus donos por nome. Além de identificar rostos humanos, os robôs estão sendo programados para aprender nossas preferências individuais. O que permitirá que antecipem nossas necessidades pessoais ao longo do tempo.",
    "Alguns dos mais populares robôs domésticos não são frios, de metal, androids construídos para atender a porta e lavar a louça. Mas sim, em 'formato 'de bichinhos de pelúcia, projetados para fazer companhia. A robô terapia vêm em forma de lontras, gatos e focas. Ao contrário dos outros animais de brinquedo, esses robôs possuem o propósito de servirem como animais de terapia, proporcionando conforto às pessoas que lidam com graves doenças, como câncer, demência, transtorno de estresse pós-traumático...",
    "Os robôs domésticos ainda ganharão muito espaço na vida das pessoas, especialmente em suas casa. Apesar de parecer história de ficção científica, acredita-se que até 2020, uma a cada 10 casas possuem um robô doméstico, para ajudar nas tarefas de casa.",
    "O investimento na Google Assistente, pela Google, é para fazer as coisas acontecerem no mundo real. No palco da Google I/O 2018, Sundar Pichai, CEO do Google, mostrou a seguinte situação: o usuário pede para a assistente marcar um horário no cabeleireiro. A partir disso, o app liga para o salão e conclui a ação. O pedido foi feito de forma natural, compreendendo tudo que a pessoa do outro lado da linha falou e dando, inclusive, respostas engraçadinhas.",
    "Robôs não estão apenas no mundo físico. Inteligência artificial da Google é capaz de reconhecer os seus hábitos e costumes, fazendo com que a bateria do celular que possui Android possa durar mais, por exemplo.",
    "A palavra robô foi pela primeira vez usada pelo escritor Checo Karel Capek em 1921, uando editou seu livro R.U.R (Rossum’s Universal Robots) que falava em máquinas com formato humano capazes de substituir as pessoas em trabalhos diários. A idéia básica era de que os avanços tecnológicos poderiam desumanizar as pessoas, tornando-as verdadeiros robôs. Desde então a palavra passou a ser usada para designar mecanismos em forma que imitam seres humanos (e mesmo animais) capazes de realizar tarefas de forma autônoma.",
]

export { dPrizes, jPrizes }
